### ISSUE TITLE
collective read in ParallelDataCollector hangs

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/libSplash#148]
If N processes call collective `ParallelDataCollector::read(...)` and some read zero amount of data the read call hangs.
This is the case when all process which read zero amount of data set `sizeRead` to zero and the pointer `buf` to `NULL`. e.g.
``` C++
void read(100, "dataName", Dimensions ( 0, 0, 0), NULL)
```

The BUG is triggered by [this](https://github.com/ComputationalRadiationPhysics/libSplash/blob/dev/src/DCDataSet.cpp#L456) check because not all read calls arrive `H5Dread`. This is not allowed if collective operations are used.

**Comment by ax3l** [comment]
As mentioned [here](https://github.com/ComputationalRadiationPhysics/picongpu/pull/611#issuecomment-69154817) we could add a test for that case.
