### ISSUE TITLE
libsplash make install error

### ISSUE THREAD

**Issue by wolfbill** [ComputationalRadiationPhysics/libSplash#168]
When I run make install I got the error:
[100%] Building CXX object CMakeFiles/domain_read.cpp.out.dir/domain_read/domain_read.cpp.o
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:24:27: error: splash/splash.h: No such file or directory
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:26: error: 'splash' is not a namespace-name
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:26: error: expected namespace-name before ';' token
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp: In function 'int main(int, char**)':
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:50: error: 'DomainCollector' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:50: error: expected ';' before 'dc'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:51: error: 'DataCollector' has not been declared
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:51: error: expected ';' before 'fAttr'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:52: error: 'DataCollector' has not been declared
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:52: error: 'fAttr' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:54: error: 'DataCollector' has not been declared
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:56: error: 'dc' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:59: error: 'int32_t' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:59: error: 'ids' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:69: error: expected type-specifier before 'int32_t'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:69: error: expected ';' before 'int32_t'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:75: error: 'DataCollector' has not been declared
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:75: error: 'entries' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:81: error: type '<type error>' argument given to 'delete', expected pointer
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:86: error: expected type-specifier before 'DataCollector'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:86: error: expected ';' before 'DataCollector'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:91: error: 'DataCollector' has not been declared
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:91: error: expected ';' before 'first_entry'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:92: error: 'first_entry' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:95: error: 'Domain' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:95: error: expected ';' before 'domain'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:96: error: 'DomainCollector' is not a class or namespace
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:96: error: expected ';' before 'dataClass'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:97: error: 'DataContainer' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:97: error: 'container' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:98: error: 'domain' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:98: error: 'dataClass' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:111: error: 'DomainData' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:111: error: 'subdomain' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:112: error: 'Dimensions' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:112: error: expected ';' before 'size'
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:114: error: 'size' was not declared in this scope
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:121: error: type '<type error>' argument given to 'delete', expected pointer
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:123: error: type '<type error>' argument given to 'delete', expected pointer
> /usr/local/src/libSplash-1.2.4/examples/domain_read/domain_read.cpp:124: error: type '<type error>' argument given to 'delete', expected pointer
> make[2]: *** [CMakeFiles/domain_read.cpp.out.dir/domain_read/domain_read.cpp.o] Error 1
> make[1]: *** [CMakeFiles/domain_read.cpp.out.dir/all] Error 2
> make: *** [all] Error 2

My software environment:
System:rhel6.4
openmpi:1.5.4

**Comment by psychocoderHPC** [comment]
Please provide use  with the following information's:
- goto the source code folder and run
  - `git rev-parse HEAD`
  - `git status -sb`
- goto your build folder:
  - remove all files `rm -r *`
  - run again your cmake command:
    - post your cmake command
    - post the cmake output
- run `make install` and post the output

**Comment by ax3l** [comment]
pls always provide all the information written above from @psychocoderHPC so we have a chance to understand your problem :)

from a very dusty view, it looks like you tried to build the examples without installing and setting up the environment of `libSplash` first: see our [INSTALL](https://github.com/ComputationalRadiationPhysics/libSplash/blob/dev/INSTALL.md#compiling) guide (last paragraph: *configure your environment variables*) .

**Comment by ax3l** [comment]
I will close the issue for now since no further problems where reported and new versions are released.

**Comment by ax3l** [comment]
note:

tested compile & install again today on lawrencium (LBNL):

- libSplash release `1.3.1`
- Scientific Linux release 6.5 (Carbon)
- gcc 4.4.7
- parallel HDF5 1.8.11
- openmpi 1.6.5

results:
- [x] library: builds and installs

- [ ] tests: build fails
- [x] examples: builds & runs

**Comment by ax3l** [comment]
@wolfbill I think you did build the examples `cmake ~/path/to/libSplash/examples`.

In this case, you do not need to hit "make install` since the created binaries can be executed directly from your build directory.

**Comment by wolfbill** [comment]
Thank you.The problem has been solved now.

**Comment by ax3l** [comment]
thank you for the information! glad it works for you :sparkles:
