### ISSUE TITLE
Simple Dataspaces for Attributes

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/libSplash#170]
@f-schmitt-zih Is it currently possible to write an attribute that consists of a fixed number of base types, e.g., 7 doubles? (I am not sure libSplash already supports that, basic HDF5, h5py and ADIOS 1.9+ does.)

This is necessary for initial openPMD support, so users can flavor their output accordingly (see `unitDimension` attribute).

Python example with h5py:
```python
record.attrs["unitDimension"] = \
    np.array([-3.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0 ], dtype="float64")
    #           L    M    T    I  theta  N    J
    # C / m^3 = A * s / m^3 -> M^-3 * T * I
```

**Comment by psychocoderHPC** [comment]
I think at the moment it is not possible, but if you add `double7` [here](https://github.com/ComputationalRadiationPhysics/libSplash/blob/dev/src/include/splash/basetypes/basetypes_compound.hpp#L61) it is.

**Comment by psychocoderHPC** [comment]
If you need a real array and no compound type you can implement a new type like the old splash `bool` implementation https://github.com/ComputationalRadiationPhysics/libSplash/blob/e64a7aafadf6143b0ce3a2f5427707a1cb4a2e15/src/include/splash/basetypes/ColTypeBool.hpp

**Comment by ax3l** [comment]
good idea, let me write a test to see if it's compatible with h5py

**Comment by psychocoderHPC** [comment]
I updated my last comment!

**Comment by psychocoderHPC** [comment]
example how we used it in PIConGPU https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/plugins/hdf5/WriteSpecies.hpp#L58

**Comment by ax3l** [comment]
I saw your update, I am talking about `TYPE_ARRAY` ;)

**Comment by ax3l** [comment]
Hm, I expected that.

For arrays, example diff:
```diff

```

libSplash creates (h5dump -H)
```
            ATTRIBUTE "unitDimension" {
               DATATYPE  H5T_ARRAY { [7] H5T_IEEE_F64LE }
               DATASPACE  SCALAR
            }
```
which can not be read via h5py
```
Traceback (most recent call last):
    d = f["data/0/datasets"].attrs["unitDimension"]
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/attrs.py", line 58, in __getitem__
    attr.read(arr)
  File "h5a.pyx", line 350, in h5py.h5a.AttrID.read (h5py/h5a.c:4626)
TypeError: Numpy array rank 1 must match dataspace rank 0.
```

but it should actually be an
```
                  ATTRIBUTE "unitDimension" {
                     DATATYPE  H5T_IEEE_F64LE
                     DATASPACE  SIMPLE { ( 7 ) / ( 7 ) }
                  }
```

interesting: that is the difference between both in hdfview:
![arrayattribsplash](https://cloud.githubusercontent.com/assets/1353258/7422357/8ff6e5cc-ef8c-11e4-9bf1-d3381ba41b03.png)

**Comment by ax3l** [comment]
trying again with `TYPE_COMPOUND`...

**Comment by ax3l** [comment]
What we should actually use instead of compounds, which are more for mixing types, are [HDF5 Simple Dataspaces](https://hdfgroup.org/HDF5/doc/UG/UG_frame12Dataspaces.html):
```
A simple dataspace, H5S_SIMPLE, is a multidimensional array of elements. The dimensionality of the dataspace (or the rank of the array) is fixed and is defined at creation time. The size of each dimension can grow during the life time of the dataspace from the current size up to the maximum size. Both the current size and the maximum size are specified at creation time. The sizes of dimensions at any particular time in the life of a dataspace are called the current dimensions, or the dataspace extent. They can be queried along with the maximum sizes.
```

**Comment by ax3l** [comment]
I am implementing `TYPE_SIMPLE` already... cool, they even allow multi-dimensional [simple dataspaces](https://hdfgroup.org/HDF5/doc/RM/RM_H5S.html#Dataspace-CreateSimple) ^^

**Comment by ax3l** [comment]
Working quick & dirty preview:
  https://github.com/ax3l/libSplash/commit/b64d3b50077416ca338aa74deeb927a1e3834c0b

**Comment by psychocoderHPC** [comment]
H5view has some bugs with compount types and might be with arrays, so don't thrust h5view!

**Comment by ax3l** [comment]
> H5view has some bugs with compount types and might be with arrays, so
> don't thrust h5view!


that's why I posted the trustworthy h5dump outputs ;)

**Comment by ax3l** [comment]
close with #171
