### ISSUE TITLE
Add Recognition for new DCDataTypes

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/libSplash#174]
We need to add enums and the general recognition in Splash for the new data types:

- DCDT_BOOL: #153 #198
- DCDT_CHAR, DCDT_STRING, DCDT_VLSTRING: #167
- ARRAY and COMPOUNDS?

- [x] At least [the following files](https://github.com/ax3l/libSplash/commit/a34235ccf75466ec3fa4959c81d2edbc8e0e4bc3) need an update.
- [x] Also, tests should be added that actually use `DCDataSet::getDCDataType()` and `DomainData::getFormatString()` (probably, both are only used in `splash2txt` -> splashtools)

**Comment by f-schmitt-zih** [comment]
Yes, they are most likely only used in the tool.
Looks good in general, chars and bools should be easy. I am not as sure about the array types etc.

**Comment by ax3l** [comment]
The array and compound types are new types, if we need them one could add them, too (I added a collection of the necessary commands in [a draft](https://github.com/ax3l/libSplash/commit/a34235ccf75466ec3fa4959c81d2edbc8e0e4bc3), but especially compounds are cumbersome...)

**Comment by ax3l** [comment]
Closed with #203
