### ISSUE TITLE
CMAKE examples: build for domain_write missing

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/libSplash#202]
The current CMake in `examples` creates a makefile for the `domain_read` but not for the `domain_write`. How do you test writing data?

**Comment by PrometheusPi** [comment]
Since I am in need for a test for writing hdf5 data with libSplash to test `/scratch` on taurus, how do you compile `domain_write` by hand?

**Comment by psychocoderHPC** [comment]
I looked to the `CMakeLists.txt` file and it looks like if you run `make` you get compiled both examples.

**Comment by PrometheusPi** [comment]
If I run `cmake .` in `examples`, then `make` I only get:
```
domain_read.cpp.out
```
next to the CMake files/caches.

(I am using the `master` version - but there has only be a minor change since 1.2.4)

**Comment by psychocoderHPC** [comment]
Please revert all your changes in examples and than try to build everything out of source.
- create a build folder
- `cd build`
- `cmake PATHTOSRC/examples`
- `make`

**Comment by PrometheusPi** [comment]
If I follow your steps I get:

**files in `build`:**
```
CMakeCache.txt  CMakeFiles  cmake_install.cmake  domain_read.cpp.out  Makefile
```
**in `CMakeFiles`:**
```
3.3.1              CMakeDirectoryInformation.cmake  CMakeTmp                 feature_tests.bin  feature_tests.cxx  Makefile.cmake  TargetDirectories.txt
cmake.check_cache  CMakeOutput.log
```

**Comment by PrometheusPi** [comment]
There is no executable for `domain_write`

**Comment by psychocoderHPC** [comment]
There is no write example without MPI.
To create the parallel write and read examples please run the following command:
`cmake PATHTOSPLASH/examples -DWITH_MPI=ON`

**Comment by PrometheusPi** [comment]
@psychocoderHPC Thank you! With mpi on it compiled.

**Comment by PrometheusPi** [comment]
If I run the executable (on slurm):
```
srun -K1 /home/s0134766/test/domain_write_mpi.cpp.out test 2 2 1
```

I get the following files:
```
test_0_0_0.h5  test_0_1_0.h5  test_1_0_0.h5  test_1_1_0.h5
```

This looks like the pre-GordonBellRun setup.
Is there a option to generate parallel output by writing a single file as we currently do with PIConGPU?

**Comment by ax3l** [comment]
> This looks like the pre-GordonBellRun setup.

This is the file based "serial" HDF5 output.

We now use the PHDF5 output (based on MPI-I/O), aka "parallel" libSplash.

unfortunately, there is no `ParallelDomainCollector` example but you can (mis)use one of the tests like this:

```bash
cd build
cmake ~/path/to/splash/tests
make
```

e.g., `Parallel_DomainsTest` uses a `ParallelDomainCollector`:
```bash
mkdir h5
mpirun -n 8 ./Parallel_DomainsTest.cpp.out
```

**Comment by ax3l** [comment]
Nevertheless, if you are looking for an example only, `PIConGPU` shippes an easy one in [the phase space plugin](https://github.com/ComputationalRadiationPhysics/picongpu/blob/985bbc1358f92917acc2cb788ee733c13a0730ff/src/picongpu/include/plugins/PhaseSpace/DumpHBufferSplashP.hpp)

**Comment by ax3l** [comment]
@PrometheusPi if there are no more questions you an lose this question.

A general relaxation of the test & example build process is planned in #197

**Comment by PrometheusPi** [comment]
@ax3l The issue can be closed. However, I am not a maintainer of libSplash, thus you have to close it.

**Comment by ax3l** [comment]
ok. note: you don't need maintainer rights to close your own issues on any repo, afaik.
