### ISSUE TITLE
openPMD: SDC globalAttributes still in /custom

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/libSplash#219]
Global attributes written with the **Serial Data Collector** are written to `/custom` not to `/` as required by openPMD. 
This can not be (simply) fixed by changing `SDC_GROUP_CUSTOM` from `/custom` to `/` in [sdc_defines.hpp](https://github.com/ComputationalRadiationPhysics/libSplash/blob/985e30a0fad3cc0c13bdd02eeeb1a7981ed14f75/src/include/splash/sdc_defines.hpp#L33).

**Comment by PrometheusPi** [comment]
If the `SDC_GROUP_CUSTOM` in  in [sdc_defines.hpp](https://github.com/ComputationalRadiationPhysics/libSplash/blob/985e30a0fad3cc0c13bdd02eeeb1a7981ed14f75/src/include/splash/sdc_defines.hpp#L33). is changed to `"/"`, the `writeGlobalAttributes()` in [SerialDataCollector.hpp](https://github.com/ComputationalRadiationPhysics/libSplash/blob/18ff55ea64dfacf2d68694cfae508c2be57ec7f4/src/SerialDataCollector.cpp#L242-L269) fails. Opening the `custom_group` ([here](https://github.com/ComputationalRadiationPhysics/libSplash/blob/18ff55ea64dfacf2d68694cfae508c2be57ec7f4/src/SerialDataCollector.cpp#L259)) fails with [this exception](https://github.com/ComputationalRadiationPhysics/libSplash/blob/18ff55ea64dfacf2d68694cfae508c2be57ec7f4/src/DCGroup.cpp#L107-L108).

**Comment by ax3l** [comment]
@f-schmitt-zih do you know by coincidence how we can migrate the `/custom` group to `/` instead?

This will introduce the assumption that `writeGlobalAttribute` in SDC is really writing a global, attribute and not a local, rank-specific one.
We can still use the current implementation as a `writeCustromAttribute` for SDC.

**Comment by ax3l** [comment]
changed in https://github.com/ax3l/libSplash/tree/topic-sdcGlobalAttrPath for the `1.4.0` release.
