### ISSUE TITLE
Attribute Writing: Create Group if Missing

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/libSplash#231]
Similar to `createReference` we need a very simple and stupid API to create an empty group for [constant openPMD records](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#constant-record-components). Right now, `writeAttribute` calls fail if the group (or data set) do not yet exist (instead of, e.g., creating the group).

@f-schmitt-zih  Is there such an API yet?

Otherwise we need to add it :)

**Comment by ax3l** [comment]
ccing @slizzered just in case you still love libSplash hacking to get your head off ;)

**Comment by f-schmitt-zih** [comment]
I don't think there is a way to do that. I just wanted to try, but the following fails on Ubuntu 14.04 with libsplash master because it doesn't find hdf5:
Apt-get install libhdf5-openmpi-7
Cmake

**Comment by ax3l** [comment]
Hm, trusty ships [1.8.11](http://packages.ubuntu.com/trusty/libhdf5-openmpi-7) which is new enough. We are compiling on precise with [travis](https://github.com/ComputationalRadiationPhysics/libSplash/blob/master/.travis.yml) for now.

You might want to search in [`/usr/lib/x86_64-linux-gnu/`](http://packages.ubuntu.com/trusty/amd64/libhdf5-openmpi-7/filelist) via `CMAKE_PREFIX_PATH`, too. (Or cmake is too old?)

**Comment by ax3l** [comment]
P.S.: my current work-around is to write a dummy variable inside the group I want to get, but that is not ideal :)

**Comment by f-schmitt-zih** [comment]
I think the easiest solution will be to allow writeAttribute to create the
group, just as a normal dataset write does. You would only need a new api
if you want to create empty groups without attributes and datasets, which
doesn't seem to make sense. Updating writeAttribute also doesn't seem to
break any compatibility.

**Comment by ax3l** [comment]
Sounds good, so we just change the behaviour of `write[Global]Attribute`.
