### ISSUE TITLE
DataContainer reads wrong offset

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/libSplash#254]
When reading a domain with DomainCollectors putting the result via `addDomain` to a `DataContainer` the offset in the container is determined falsely (always 0,0,0).

logic error in libSplash when reading offsets:
- default = 0,0,0 https://github.com/ComputationalRadiationPhysics/libSplash/blob/563da86e62fc483d214bed4163140b15f4957abe/src/include/splash/domains/DataContainer.hpp#L48
- min with values > 0 will never be the correct offset: https://github.com/ComputationalRadiationPhysics/libSplash/blob/563da86e62fc483d214bed4163140b15f4957abe/src/include/splash/domains/DataContainer.hpp#L86

Related to https://github.com/ComputationalRadiationPhysics/picongpu/issues/1544

**Comment by Flamefire** [comment]
Idea for a fix: If the first entry is added then  init offset to the entrys offset. Would only be 2 lines added.

**Comment by ax3l** [comment]
that could work, but I did not check the full logics it will touch yet.

maybe we add a (currently failing) test first and then implement that by checking `subdomains.size()` for the first add?
