### ISSUE TITLE
Warning in H5IdWrapper

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/libSplash#265]
The current (pre 1.7.0-dev) causes the following warning with GCC 4.9.2 in PIConGPU:

```
include/splash/core/H5IdWrapper.hpp(39): warning: variable "copyNotAllowed" was set but never used
```

**Comment by Flamefire** [comment]
Strange. This line (https://github.com/ComputationalRadiationPhysics/libSplash/pull/248/files#diff-76c3ec9bcec7a4eb129e6c36f5699bdaR40) should avoid this. Don't know how else to do it. Maybe simply make it inherit from the policy and make the copy CTor private

**Comment by ax3l** [comment]
I know and that usually works... could be ineffective do to it's `static`-ness.
